version: "3.3"

services:
  ldap:
    build: ./ldap_server/
    environment:
      - PORT=1389
      - BASE_DN=dc=didm,dc=be
      - ROOT_PASSWORD=secret
      - ROOT_USER_DN=cn=admin,dc=didm,dc=be
    ports:
      - 1389:1389
    networks:
     - net

  postgres_resource:
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/src_database_password.txt
      - POSTGRES_USER=pgres
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 8432:8432
    command: -p 8432
    networks:
      - net
    secrets:
      - src_database_password.txt
    volumes:
      - source_data:/var/lib/postgresql/data
      - ./configs-and-secrets/source-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  midpoint_data:
    image: postgres:11.6
    environment:
     - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - POSTGRES_USER=midpoint
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
     - 5432:5432
    networks:
     - net
    secrets:
     - mp_database_password.txt
    volumes:
     - midpoint_data:/var/lib/postgresql/data

  midpoint_server:
    build: ./midpoint_server/
    depends_on:
     - midpoint_data
     - postgres_resource
    ports:
      - 8080:8080
      - 8000:8000
    environment:
     - REPO_DATABASE_TYPE=postgresql
     - REPO_HOST=midpoint_data
     - REPO_DATABASE=midpoint
     - REPO_USER=midpoint
     - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - REPO_MISSING_SCHEMA_ACTION=create
     - REPO_UPGRADEABLE_SCHEMA_ACTION=stop
     - REPO_SCHEMA_VERSION_IF_MISSING
     - REPO_SCHEMA_VARIANT
     - MP_KEYSTORE_PASSWORD_FILE=/run/secrets/mp_keystore_password.txt
     - MP_MEM_MAX=2048m
     - MP_MEM_INIT=1024m
     - MP_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
     - TIMEZONE=UTC
    networks:
     - net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
    volumes:
     - midpoint_home:/opt/midpoint/var

networks:
  net:    
    driver: bridge

secrets:
  src_database_password.txt:
    file: ./configs-and-secrets/source-db/database_password.txt
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/keystore_password.txt
    
volumes:
  source_data:
  midpoint_data:
  midpoint_home:
